### ISSUE TITLE
Doesn't works on Windows

### ISSUE THREAD

**Issue by Flashwalker** [raphaelquintao/QColor#1]
Doesn't works on Windows

Log:
```
DPI mode: per-monitor v2
startup, version: 4107 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
application: /C/Program Files/Sublime Text 3
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/design/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/design/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/design/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Color Highlighter", "Vintage", "Color Highlight"]
pre session restore time: 0.271344
warning: mnemonic t not found in menu caption Tools
warning: mnemonic c not found in menu caption QColor
warning: mnemonic p not found in menu caption Preferences
warning: mnemonic c not found in menu caption QColor
warning: mnemonic t not found in menu caption Tools
warning: mnemonic c not found in menu caption QColor
warning: mnemonic p not found in menu caption Preferences
warning: mnemonic c not found in menu caption QColor
startup time: 0.373344
first paint time: 0.375344
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin A File Icon.plugin
reloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading python 3.3 plugin 0_package_control_loader.01-pygments
reloading python 3.3 plugin 0_package_control_loader.50-backrefs
reloading python 3.3 plugin 0_package_control_loader.50-markupsafe
reloading python 3.3 plugin 0_package_control_loader.50-pymdownx
reloading python 3.3 plugin 0_package_control_loader.50-python-markdown
reloading python 3.3 plugin 0_package_control_loader.50-pyyaml
reloading python 3.3 plugin 0_package_control_loader.51-python-jinja2
reloading python 3.3 plugin 0_package_control_loader.55-mdpopups
reloading python 3.3 plugin ayu.activation
reloading python 3.3 plugin ayu.Icons
reloading python 3.3 plugin BracketHighlighter.bh_core
reloading python 3.3 plugin BracketHighlighter.bh_logging
reloading python 3.3 plugin BracketHighlighter.bh_plugin
reloading python 3.3 plugin BracketHighlighter.bh_popup
reloading python 3.3 plugin BracketHighlighter.bh_regions
reloading python 3.3 plugin BracketHighlighter.bh_remove
reloading python 3.3 plugin BracketHighlighter.bh_rules
reloading python 3.3 plugin BracketHighlighter.bh_search
reloading python 3.3 plugin BracketHighlighter.bh_swapping
reloading python 3.3 plugin BracketHighlighter.bh_wrapping
reloading python 3.3 plugin BracketHighlighter.support
reloading python 3.3 plugin Increment Decrement.increment_decrement
reloading python 3.3 plugin Package Control.1_reloader
reloading python 3.3 plugin Package Control.2_bootstrap
reloading python 3.3 plugin Package Control.Package Control
reloading python 3.3 plugin PackageResourceViewer.package_resource_viewer
reloading python 3.3 plugin PackageResourceViewer.package_resources
reloading python 3.3 plugin ColorPicker.sublimecp
reloading python 3.3 plugin LiveReload.__init__
enabled_plugins
LiveReload: added file /livereload.js with content-type: text/javascript
reloading python 3.3 plugin LiveReload.CoffeescriptPlugin
reloading python 3.3 plugin LiveReload.CommandAPI
enabled_plugins
reloading python 3.3 plugin LiveReload.CompassPlugin
INFO:WebSocketClient:Starting server
reloading python 3.3 plugin LiveReload.LESSPlugin
reloading python 3.3 plugin LiveReload.LiveReload
reloading python 3.3 plugin LiveReload.SimpleReloadCallback
reloading python 3.3 plugin LiveReload.SimpleReloadPlugin
reloading python 3.3 plugin LiveReload.SimpleReloadPluginDelay
reloading python 3.3 plugin LiveReload.SimpleWSCallback
reloading python 3.3 plugin LiveStyle.livestyle-plugin
reloading python 3.3 plugin QColor.QColor
plugins loaded
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] Не удается найти указанный файл

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\Lib\python33\sublime_plugin.py", line 528, in on_api_ready
    plc()
  File "C:\Users\design\AppData\Roaming\Sublime Text 3\Packages\QColor\QColor.py", line 89, in plugin_loaded
    if check_deps():
  File "C:\Users\design\AppData\Roaming\Sublime Text 3\Packages\QColor\QColor.py", line 64, in check_deps
    proc = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] Не удается найти указанный файл
LiveStyle: Start app
generating syntax summary
LiveStyle: Client connection error: [Errno 10061] Unknown error
LiveStyle: Create own server on port 54000
LiveStyle: Starting LiveStyle server on port 54000
LiveStyle: Client connected
Package Control: Detected Sublime Text update, looking for package updates
Package Control: No updated packages
warning: mnemonic t not found in menu caption Tools
warning: mnemonic c not found in menu caption QColor
warning: mnemonic p not found in menu caption Preferences
warning: mnemonic c not found in menu caption QColor
```

```
>> import webview
Traceback (most recent call last):
  File "__main__", line 1, in <module>
ModuleNotFoundError: No module named 'webview'

```

But if I go to the sublime settings file and add QCcolor to ignored packages there and save it, then at the time the file is saved, the QColor plugin starts  (but asks to install pywebview via pip3, which is not about Windows), but this brings huge lags to editor.

**Comment by raphaelquintao** [comment]
Hi Man, 
Sorry about the delay, i just saw you issue today.
Pip also works on Windows, you can follow some online tutorials to install it.
You can easily find on [Google](https://www.google.com/search?q=python+pip+windows) how to install it.
