### ISSUE TITLE
didn't work sublime 4

### ISSUE THREAD

**Issue by basaran** [raphaelquintao/QColor#2]
Hello,

After installing the pywebview:

```
>>> import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/hello')
webview.start()
Traceback (most recent call last):
  File "__main__", line 1, in <module>
ModuleNotFoundError: No module named 'webview'
```

and Qcolor debug

```
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/michael/.config/sublime-text/Packages/QColor/QColor.py", line 345, in on_conf_change
    self.start()
  File "/home/michael/.config/sublime-text/Packages/QColor/QColor.py", line 333, in start
    self.on_view_change()
  File "/home/michael/.config/sublime-text/Packages/QColor/QColor.py", line 364, in on_view_change
    self.show_phantoms()
  File "/home/michael/.config/sublime-text/Packages/QColor/QColor.py", line 411, in show_phantoms
    if not self.isEnabled(): return False
  File "/home/michael/.config/sublime-text/Packages/QColor/QColor.py", line 310, in isEnabled
    return _conf.get(self.key_ctrl, True)
AttributeError: 'NoneType' object has no attribute 'get'
warning: mnemonic t not found in menu caption Tools
warning: mnemonic c not found in menu caption QColor
warning: mnemonic p not found in menu caption Preferences
warning: mnemonic c not found in menu caption QColor
``

**Comment by raphaelquintao** [comment]
Hi, 
I will take a look at this.
Are you using Linux or Mac?

**Comment by basaran** [comment]
Yes, miraculously, after uninstalling it, it started to work :) Literally, removed the package (without installing again) I saw the colors pop. Then installed it again, and it seems fine now. 

Perhaps it's because I didn't have the pywebview installed prior to installing the qcolor?
